config/routes.rb
Rails.application.routes.draw do
  root to: 'maps#index'
  resources :maps, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/map_request', to: 'maps#map', as: 'map_request'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
  end


  def map


    uri = URI.escape("https://maps.googleapis.com/maps/api/geocode/json?address="+params[:address]+"&key=AIzaSyAXVO_qAdBaE7xi7UQgs_uUnXFKNv1U7go")
    res = HTTP.get(uri).to_s
    response = JSON.parse(res)
    #@latlngに空の箱を渡している。
    @latlng = []
    #右から順に取得した緯度経度を渡している。
    @latlng << response["results"][0]["geometry"]["location"]["lat"]
    @latlng << response["results"][0]["geometry"]["location"]["lng"]
    # results = Geocoder.search(params[:address])
  # @latlng = results.first.coordinates
#これでmap.js.erbで、経度緯度情報が入った@latlnpを使える。

  # respond_to以下の記述によって、
  # remote: trueのアクセスに対して、
  # map.js.erbが変えるようになります。
  respond_to do |format|
  format.js
  end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GmapTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/maps/index.html.erb
<h2>gmap</h2>
<!-- form_withはデフォルトでremote: trueの挙動になります -->
<%= form_with url: map_request_path, method: :get do |f|%>
  <%= f.text_field :address %>
  <%= f.submit '地図表示' %>
<% end %>

<div id='map'></div>

<style>
#map{
  height: 400px;
}
</style>

<script>
let mapInstance //この変数はmap.js.erbでも使うのでタイプミスに注意
function initMap(){
    mapInstance = new google.maps.Map(document.getElementById('map'), {
    center: {lat: -34.397, lng: 150.644},
    zoom: 8
    });
  }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAXVO_qAdBaE7xi7UQgs_uUnXFKNv1U7go&callback=initMap" async defer></script>

app/views/maps/map.js.erb
(function(){
  // 位置情報をもつ変数を用意
  let pos = new google.maps.LatLng(
   <%= @latlng[0] %>, //latitude
   <%= @latlng[1] %>  //longitude
  );

  mapInstance.setCenter(pos)
  let marker = new google.maps.Marker({
    map: mapInstance,
    position: pos
  });
})()